  ---
  - hosts: localhost
    gather_facts: false
    vars_files:
      - vars.yml

    tasks:
      - name: Launch a EC2 instance Using Ansible Playbook
        ec2:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          key_name: firstkey
          instance_type: t2.micro
          image: ami-0d1cd67c26f5fca19
          wait: yes
          count: 1
          region: us-west-1
          volumes: 
            - device_name: /dev/xvda
              ebs: 
                volume_size: 8
                volume_type: gp2
          tags:
            - Launch_ec2_instance_using_ansible